### ISSUE TITLE
reading other attributes of article

### ISSUE THREAD

**Issue by protw** [otavio-s-s/data_science#3]
Hello, Otavio. 

First, let me express my admiration for your elegant and useful utility `mediumScraper.py`

In 2021 I deeply dived into both _Python_ and _Medium_. I've recently admired the idea to launch a _Medium Publication_. For this, reading attributes and the stats of each article in a Publication is the essential part. 

Your utility fits quite well for this purpose except it lacks reading of several attributes of an article, namely: kicker, tags, number of views and number of readings.

Despite I can read HTML elements and selectors of a Medium article page, nevertheless I could not comprehend how these selectors are logically connected with argument `copy_` in function `story.find()`.

Could you help me in understanding how to fetch these data from the article?

Also, I can guess, that the number of views and the number of readings are likely not stored (even hiddenly) on the same web-page with the article's text. Nevertheless, could you point me out to a proper direction how to find them as well.

All the best in the New Year 2022.

Sincerely,
Olegh

P.S.

In line 25 please change instead of:

`date = f'{month}/{day}/2019'`

to:

`date = f'{month}/{day}/{year}'`

**Comment by otavio-s-s** [comment]
Hi, Olegh.

Thanks for the message. I'm glad you liked my work.

1- Kicker and tags can be easily collected from the article page. You just need to locate their elements on the HTML:

![image](https://user-images.githubusercontent.com/60897189/147929574-0b88bfa1-66d4-454f-b773-b6cc3abb9d5d.png)

![image](https://user-images.githubusercontent.com/60897189/147929664-4933123e-f62d-4783-ba14-880aaaa0c4a3.png)

You only have to implement a `for` loop to get all the tags, something like this:

![image](https://user-images.githubusercontent.com/60897189/147929967-e3f3efc7-858c-446a-a9c8-fd426601ce2b.png)

And then you'll have a list with all the tags.

2- I did not understand your point about the argument `copy_` in the function `story.find()` as I did not use it.

3- I really don't think the numbers of reads and views are available. I even checked directly in the API responses from the backend and could not find it.

Let me know if I can further help you.

Best,
Otávio.


P.S.: fixed.

**Comment by protw** [comment]
Hello, Otavio.

1) Please excuse me the confusion about argument: it must have been `class_` instead of `copy_`.

2) Regarding the kicker - I know how to locate HTML-code of any element of a web-page in a browser. But I wonder about the logical link between the element selector and the argument `class_` value for the chosen element.

3) Regarding your code fragment for the tag list. 

    - First, object `quote` (in `tags = quote.find('div', class_='tags').find_all('a')`) is not defined in `mediumScraper.py`.
    - Second, I've tried to change the unknown `quote` to the known `story` but encountered the following error: `AttributeError: 'NoneType' object has no attribute 'find_all'`
  
I'd be grateful for your assistance.

Olegh

**Comment by otavio-s-s** [comment]
`class_` is where you specify the class of HTML element to the function. Notice that the kicker has a `class` attribute in the HTML. That's what you'll pass to the `class_` argument.

About the tag, that was just an example of how you'd implement it, not a real implementation. Use the same logic and you'll be successful.

**Comment by protw** [comment]
Eventually it works like this:

```
url_arc = f'{url}/archive/{year}/{month}/{day}'
page = requests.get(url_arc)
...
tags = story_soup.find_all('a')
tags_list = []
for tag in tags:
    if (url + '/tagged/') in tag['href']:
        tags_list.append(tag.text)
```
Thanks
